"""create gulls gull_trackpoints weather_observations tables

Revision ID: b392ef6deb9b
Revises: 
Create Date: 2026-03-13 02:16:56.630818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b392ef6deb9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gulls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=150), nullable=False),
    sa.Column('common_name', sa.String(length=150), nullable=True),
    sa.Column('study_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gulls_id'), 'gulls', ['id'], unique=False)
    op.create_index(op.f('ix_gulls_species'), 'gulls', ['species'], unique=False)
    op.create_index(op.f('ix_gulls_tag_id'), 'gulls', ['tag_id'], unique=True)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('wind_u', sa.Float(), nullable=True),
    sa.Column('wind_v', sa.Float(), nullable=True),
    sa.Column('surface_pressure', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)
    op.create_index(op.f('ix_weather_observations_observed_at'), 'weather_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_weather_observations_year'), 'weather_observations', ['year'], unique=False)
    op.create_index('ix_weather_observed_at_lat_lon', 'weather_observations', ['observed_at', 'latitude', 'longitude'], unique=False)
    op.create_table('gull_trackpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gull_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('sensor_type', sa.String(length=100), nullable=True),
    sa.Column('visible', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['gull_id'], ['gulls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gull_trackpoints_gull_id'), 'gull_trackpoints', ['gull_id'], unique=False)
    op.create_index('ix_gull_trackpoints_gull_recorded_at', 'gull_trackpoints', ['gull_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_gull_trackpoints_id'), 'gull_trackpoints', ['id'], unique=False)
    op.create_index(op.f('ix_gull_trackpoints_recorded_at'), 'gull_trackpoints', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gull_trackpoints_recorded_at'), table_name='gull_trackpoints')
    op.drop_index(op.f('ix_gull_trackpoints_id'), table_name='gull_trackpoints')
    op.drop_index('ix_gull_trackpoints_gull_recorded_at', table_name='gull_trackpoints')
    op.drop_index(op.f('ix_gull_trackpoints_gull_id'), table_name='gull_trackpoints')
    op.drop_table('gull_trackpoints')
    op.drop_index('ix_weather_observed_at_lat_lon', table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_year'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_observed_at'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_gulls_tag_id'), table_name='gulls')
    op.drop_index(op.f('ix_gulls_species'), table_name='gulls')
    op.drop_index(op.f('ix_gulls_id'), table_name='gulls')
    op.drop_table('gulls')
    # ### end Alembic commands ###
